apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{  include "smoker.fullname" . }}2
  annotations:
    fluxcd.io/ignore: 'true'
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  schedule: '*/20 * * * *'
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: smoker2
              image: retaildevcrew/webvalidate
              imagePullPolicy: Always
              args:
                - '-s'
                - '{{ .Values.ingressURL }}'
                - '-u'
                - 'https://raw.githubusercontent.com/retaildevcrews/helium/main/TestFiles/'
                - '-f'
                - 'benchmark.json'
                - '-r'
                - '--duration'
                - '450'
                - '-l'
                - '10'
          restartPolicy: OnFailure
