# Default values for helium.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
labels:
  aadpodidbinding: %%MI_Name%% #should be value of $MI_Name from the output of aad-podid.sh

image:
  repository: retaildevcrew #The specific acr created for this environment
  name: helium-csharp # The name of the image for the helium-csharp repo
  tag: stable

annotations:
  linkerd.io/inject: enabled # Allows for the application to be injected into the Service Mesh

ingress:
  hosts:
    - paths: /

keyVaultName: %%KV_Name%% # Replace with the name of the Key Vault that holds the secrets
